name: Release
on:
  push:
    branches:
      - main

jobs:
  main:
    name: NPM Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: volta-cli/action@v1.7.0
      - name: Install dependencies
        run: npm ci
      - name: Release new version to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
